IMAGE:
  WIDTH: 640
  HEIGHT: 480
  Y_OFFSET: 380
  Y_GAP: 25
  Y_GAIN: 1.35

XYCAR:
  START_SPEED: 6.0 #5.0
  MAX_SPEED: 6.0  # 5.0
  MIN_SPEED: 6.0
  SPEED_CONTROL_THRESHOLD: 35.0
  ACCELERATION_STEP: 0.2
  DECELERATION_STEP: 0.05

PID:
  P_GAIN: 0.45 #0.35 #0.45
  I_GAIN: 0.00
  D_GAIN: 0.007 # 0.007

MOVING_AVERAGE_FILTER:
  SAMPLE_SIZE: 30

CANNY:
  LOW_THRESHOLD : 100
  HIGH_THRESHOLD : 150

HOUGH:
  MIN_PIXEL : 40  # 40
  MIN_LINE :  35   # 35
  MAX_GAP : 10

KALMAN:
  SLOPE_DER: -0.015 # -0.02
  INTERCEPT_DER: -25.0 # -3.0

TOPIC:
  PUB_NAME: /xycar_motor
  SUB_NAME: /usb_cam/image_raw/
  YOLO_NAME: /yolov3_trt_ros/detections
  # YOLO_NAME: /lidar_pub
  LIDAR_NAME: /scan
  QUEUE_SIZE: 1

DEBUG: True
